---
- name: Configure important user consistently
  hosts: all
  tasks:
    - name: Newbie exists with UID 4000
      user:
        name: newbie
        uid: 4000
        state: present
      notify:
        - User add

  handlers:
    - name: User add
      debug:
        msg: Usuario creado
      
